# Generated by Django 5.2.3 on 2025-07-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
