# Generated by Django 5.2.3 on 2025-07-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_medicinehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='who',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
