# Generated by Django 5.2.3 on 2025-07-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_patientmedicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='place',
        ),
        migrations.AddField(
            model_name='customuser',
            name='place',
            field=models.ManyToManyField(blank=True, to='main.place'),
        ),
    ]
