# Generated by Django 5.2.3 on 2025-08-01 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_place_remove_customuser_place_customuser_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.place'),
        ),
    ]
