# Generated by Django 5.2.3 on 2025-08-01 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_medicine_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinehistory',
            name='to_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.place'),
        ),
    ]
