# Generated by Django 5.2.3 on 2025-08-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_patient_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicine',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
