# Generated by Django 5.2.3 on 2025-08-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_patientmedicine_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmedicine',
            name='invoice_number',
        ),
    ]
