# Generated by Django 5.2.3 on 2025-08-19 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_patientmedicine_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinehistory',
            name='to_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_medicines', to='main.patient'),
        ),
    ]
