# Generated by Django 5.2.3 on 2025-08-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_medicinehistory_to_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
