# Generated by Django 5.2.3 on 2025-08-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_medicine_generic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='box_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
