# Generated by Django 5.2.3 on 2025-08-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_medicine_box_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='extra_units',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
