# Generated by Django 5.2.3 on 2025-08-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_medicine_extra_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmedicine',
            name='quantity',
        ),
        migrations.AddField(
            model_name='patientmedicine',
            name='boxes_given',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientmedicine',
            name='units_given',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
