# Generated by Django 5.2.3 on 2025-09-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_medicine_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('---', '---'), ('tablet', 'Tabletkalar'), ('syrup', 'Sirop'), ('vitamin', 'Vitamin'), ('inhaler', 'Ingalator')], default='---', max_length=50),
        ),
    ]
