# Generated by Django 5.2.3 on 2025-09-06 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_medicine_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dori', 'verbose_name_plural': 'Dorilar'},
        ),
        migrations.AlterModelOptions(
            name='medicinehistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dori tarixi', 'verbose_name_plural': 'Dori tarixi'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bemor', 'verbose_name_plural': 'Bemorlar'},
        ),
        migrations.AlterModelOptions(
            name='patientmedicine',
            options={'ordering': ['-date'], 'verbose_name': 'Chek', 'verbose_name_plural': 'Cheklar'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Joy', 'verbose_name_plural': 'Joylar'},
        ),
        migrations.CreateModel(
            name='StaffPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.place')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sklad',
                'verbose_name_plural': 'Sklad',
            },
        ),
    ]
