# Generated by Django 5.2.3 on 2025-09-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_customuser_options_alter_medicine_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffplace',
            name='place',
            field=models.CharField(max_length=100),
        ),
    ]
