# Generated by Django 5.2.3 on 2025-09-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_staffplace_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffPlace',
        ),
    ]
